name: theta
description: RICOH THETA WebAPI package for Dart
version: 0.1.0
author: Oppkey
homepage: https://theta360developers.github.io/webapi

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  effective_dart: ^1.0.0
